name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  grpc:
    git: git@github.com:grpc/grpc-dart.git
  protobuf: ^2.0.0
  messages:
    path: ../messages

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
