name: messages
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/MateusAmin/grpc-dart-issues-506
publish_to: none

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  grpc:
    git: git@github.com:grpc/grpc-dart.git
  protobuf: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
